### ISSUE TITLE
whole-transcriptome RNA-Seq data as input

### ISSUE THREAD

**Issue by iranmdl** [data2intelligence/Tres#1]
Hi!
Does the tool work providing as input a table with TPMs calculated using whole-transcriptome RNA-Seq data (not single-cell)? 
Thank you in advance,

**Comment by data2intelligence** [comment]
Hi, Irantzu,

Yes, but you need to do the normalization first:

1, transfer the data to log2(TPM + 1).
2, mean centralize across all conditions for each gene. i.e., for each gene, you get the mean log2(TPM+1) across all conditions, and subtract this mean value from each gene.




Sincerely, Peng


On Jun 15, 2022, at 6:55 AM, Irantzu ***@***.******@***.***>> wrote:



Hi!
Does the tool work providing as input a table with TPMs calculated using whole-transcriptome RNA-Seq data (not single-cell)?
Thank you in advance,

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdata2intelligence%2FTres%2Fissues%2F1&data=05%7C01%7Cpeng.jiang%40nih.gov%7C82ff7b08748c47a2d12008da4ebd9c58%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637908873518501403%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Mo%2BJPt2Y9sG4mXhpWstySEH91%2FBnGMNHIH7HJaz9RwE%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQRREFZXOJJUCM6EYKOIN5LVPGZDJANCNFSM5Y23I3HA&data=05%7C01%7Cpeng.jiang%40nih.gov%7C82ff7b08748c47a2d12008da4ebd9c58%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637908873518501403%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ATdIaMVyOlpHGUAyrdM%2Fz6HmAEn8Ph%2FBcri%2Flv4Ic1A%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by iranmdl** [comment]
Thanks for the quick reply!
Then, I can use directly the output of a standard expression quantification tool, apply log2(TPM+1), mean centralize the rows (genes), and run "predict" in the webserver tool? I am concerned about the "T cells or T-cell rich samples" in the description of the tool. I just have standard RNA-Seq data.

Thank you again

**Comment by data2intelligence** [comment]
Hi, Irantzu,

1, yes, after these steps, just use the web server tool or our source code.

2, the T cell or T-cell rich samples means that your RNA-Seq data should come from T cell samples or samples enriched with T cell infiltrations (as Tres is trained on T-cell gene expression).




On Jun 15, 2022, at 11:05 AM, Irantzu ***@***.******@***.***>> wrote:



Thanks for the quick reply!
Then, I can use directly the output of a standard expression quantification tool, apply log2(TPM+1), mean centralize the rows (genes), and run "predict" in the webserver tool? I am concerned about the "T cells or T-cell rich samples" in the description of the tool. I just have standard RNA-Seq data.

Thank you again

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdata2intelligence%2FTres%2Fissues%2F1%23issuecomment-1156591220&data=05%7C01%7Cpeng.jiang%40nih.gov%7Ca7e2443dd3054901a68c08da4ee08475%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637909023457605713%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9aoXqpCsa%2Bl7Sbe%2F5uKuoOCOFb2bWKJBLvh2Ack93Zk%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQRREF4ZSHA7QYMZ3MF4KEDVPHWLTANCNFSM5Y23I3HA&data=05%7C01%7Cpeng.jiang%40nih.gov%7Ca7e2443dd3054901a68c08da4ee08475%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637909023457605713%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bpDjmpI4ScAUJhBq9hYJfzYB%2BjuHaR5g1DlRsMFNa%2FI%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.***>

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.
